name: "Lampac NextGen"
description: "Self-hosted backend for Lampa."
version: "1.29.12-1"
slug: "lampac"
url: https://github.com/BrainDeLook/lampac-ha
arch:
  - aarch64
  - amd64
init: false
webui: http://[HOST]:[PORT:9118]/lampa-main/index.html
panel_icon: mdi:television-play
panel_title: "Lampac"
options:
  root_password: "changeme"
  admin_panel_url: "http://YOUR_HA_IP:9118/adminpanel/auth"
  enable_admin_panel: true
  enable_torrserver: false
  skip_modules:
    - Rezka
    - Filmix
    - Kodik
    - Alloha
    - HDVB
    - Collaps
    - Zetflix
    - ZetflixDB
    - Vibix
    - Kinoflix
    - Kinogo
    - Kinobase
    - Kinotochka
    - VoKino
    - KinoPub
    - IptvOnline
    - GetsTV
    - SakhTV
    - iRemux
    - CDNvideohub
    - Videoseed
    - RutubeMovie
    - Mirage
    - Phantom
    - PizdatoeHD
    - Spectre
    - FlixCDN
    - VeoVeo
    - VkMovie
    - LeProduction
    - VideoDB
    - FanCDN
    - UaKino
    - HdvbUA
    - Eneyida
    - KinoUkr
    - Tortuga
    - Ashdi
    - UAFilm
    - Geosaitebi
    - AsiaGe
    - VidSrc
    - AutoEmbed
    - PlayEmbed
    - SmashyStream
    - TwoEmbed
    - RgShows
    - MovPI
    - VidLink
    - HydraFlix
    - Videasy
    - BamBoo
    - AniLibria
    - AnimeGo
    - AnimeLib
    - AniMedia
    - Mikai
    - Dreamerscast
    - AnimeON
    - Animebesst
    - AniLiberty
    - Animevost
    - MoonAnime
    - JacRed
    - PidTor
    - SISI
    - PornHub
    - HQporner
    - Xvideos
    - Xhamster
    - Xnxx
    - Chaturbate
    - BongaCams
    - Runetki
    - Eporner
    - Porntrex
    - Spankbang
    - Ebalovo
    - Tizam
schema:
  root_password: str
  admin_panel_url: str
  enable_admin_panel: bool
  enable_torrserver: bool
  skip_modules:
    - "list(Rezka|Filmix|Kodik|Alloha|HDVB|Collaps|Zetflix|ZetflixDB|Vibix|Kinoflix|Kinogo|Kinobase|Kinotochka|VoKino|KinoPub|IptvOnline|GetsTV|SakhTV|iRemux|CDNvideohub|Videoseed|RutubeMovie|Mirage|Phantom|PizdatoeHD|Spectre|FlixCDN|VeoVeo|VkMovie|LeProduction|VideoDB|FanCDN|UaKino|HdvbUA|Eneyida|KinoUkr|Tortuga|Ashdi|UAFilm|Geosaitebi|AsiaGe|VidSrc|AutoEmbed|PlayEmbed|SmashyStream|TwoEmbed|RgShows|MovPI|VidLink|HydraFlix|Videasy|BamBoo|AniLibria|AnimeGo|AnimeLib|AniMedia|Mikai|Dreamerscast|AnimeON|Animebesst|AniLiberty|Animevost|MoonAnime|JacRed|PidTor|SISI|PornHub|HQporner|Xvideos|Xhamster|Xnxx|Chaturbate|BongaCams|Runetki|Eporner|Porntrex|Spankbang|Ebalovo|Tizam)"
