name: "Lampac NextGen"
description: "Self-hosted backend for Lampa."
version: "1.36.0"
slug: "lampac"
url: https://github.com/BrainDeLook/lampac-ha
arch:
  - aarch64
  - amd64
init: false
webui: http://[HOST]:[PORT:9118]/lampa-main/index.html
panel_icon: mdi:television-play
panel_title: "Lampac"
options:
  root_password: "changeme"
  admin_panel_url: "http://YOUR_HA_IP:9118/adminpanel/auth"
  enable_admin_panel: true
  enable_torrserver: false
  extra_skip_modules:
    - Kinoflix
    - Vibix
    - Collaps
    - Zetflix
    - Kinobase
    - Kinotochka
    - PizdatoeHD
    - Mirage
    - Phantom
    - CDNvideohub
    - Videoseed
    - RutubeMovie
    - Spectre
    - FlixCDN
    - VeoVeo
    - VkMovie
    - Kinogo
    - LeProduction
    - VideoDB
    - HDVB
    - ZetflixDB
    - FanCDN
    - Kodik
    - AnimeLib
    - Mikai
    - AniLibria
    - AnimeGo
    - Dreamerscast
    - AnimeON
    - AniMedia
    - Animebesst
    - AniLiberty
    - Animevost
    - MoonAnime
    - HQporner
    - Chaturbate
    - Runetki
    - PornHub
    - Tizam
    - Xnxx
    - Porntrex
    - Eporner
    - BongaCams
    - Xvideos
    - XvideosRED
    - Xhamster
    - Spankbang
    - Ebalovo
    - SISI
    - PidTor
    - PlayEmbed
    - SmashyStream
    - TwoEmbed
    - RgShows
    - VidSrc
    - AutoEmbed
    - MovPI
    - VidLink
    - HydraFlix
    - Geosaitebi
    - BamBoo
    - AsiaGe
    - HdvbUA
    - UaKino
    - Eneyida
    - KinoUkr
    - Tortuga
    - Ashdi
    - UAFilm
    - Alloha
    - GetsTV
    - SakhTV
    - KinoPub
    - IptvOnline
    - Rezka
    - iRemux
    - VoKino
    - Filmix
    - JacRed
    - Videasy
    - Potok
    - NextHUB
    - Sync
    - WatchTogether
    - WebLog
    - GStreamer
    - Tg-notify.bot
    - LogUserRequest-Lite
schema:
  root_password: str
  admin_panel_url: str
  enable_admin_panel: bool
  enable_torrserver: bool
  extra_skip_modules:
    - "list(Kinoflix|Vibix|Collaps|Zetflix|Kinobase|Kinotochka|PizdatoeHD|Mirage|Phantom|CDNvideohub|Videoseed|RutubeMovie|Spectre|FlixCDN|VeoVeo|VkMovie|Kinogo|LeProduction|VideoDB|HDVB|ZetflixDB|FanCDN|Kodik|AnimeLib|Mikai|AniLibria|AnimeGo|Dreamerscast|AnimeON|AniMedia|Animebesst|AniLiberty|Animevost|MoonAnime|HQporner|Chaturbate|Runetki|PornHub|Tizam|Xnxx|Porntrex|Eporner|BongaCams|Xvideos|XvideosRED|Xhamster|Spankbang|Ebalovo|SISI|PidTor|PlayEmbed|SmashyStream|TwoEmbed|RgShows|VidSrc|AutoEmbed|MovPI|VidLink|HydraFlix|Geosaitebi|BamBoo|AsiaGe|HdvbUA|UaKino|Eneyida|KinoUkr|Tortuga|Ashdi|UAFilm|Alloha|GetsTV|SakhTV|KinoPub|IptvOnline|Rezka|iRemux|VoKino|Filmix|JacRed|Videasy|Potok|NextHUB|Sync|WatchTogether|WebLog|GStreamer|Tg-notify.bot|LogUserRequest-Lite)"
ports:
  9118/tcp: 9118
ports_description:
  9118/tcp: Lampac API + AdminPanel (/adminpanel/auth)
map:
  - data:rw
